/**CREACION DE TABLA**/
CREATE TABLE "NOTAS" (
    "NOTA_ID"         NUMBER NOT NULL ENABLE,
    "PRIMER_PARCIAL"  NUMBER,
    "SEGUNDO_PARCIAL" NUMBER,
    "EXAMEN_FINAL"    NUMBER,
    CONSTRAINT "NOTAS_PK" PRIMARY KEY ("NOTA_ID"));
    
CREATE OR REPLACE PROCEDURE INSERTA_NOTAS AS
BEGIN
  FOR i IN 1..2000 LOOP
      INSERT INTO NOTAS (NOTA_ID, PRIMER_PARCIAL, SEGUNDO_PARCIAL, EXAMEN_FINAL)
      SELECT (SELECT NVL(MAX(NOTA_ID),0)+1 FROM NOTAS),
              trunc(ABS(dbms_random.value(0,10)),2),
              trunc(ABS(dbms_random.value(0,10)),2),
              trunc(ABS(dbms_random.value(0,10)),2)
        FROM  dual;
 END LOOP;
 COMMIT;
END INSERTA_NOTAS;


/**LLAMADA DEL PROCEDIMIENTO**/
BEGIN
  INSERTA_NOTAS();
END;